# Generated by Django 5.0.1 on 2025-04-18 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('numClasse', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=5)),
                ('groupe', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('numEtablissement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('slogant', models.CharField(max_length=255, null=True)),
                ('logo', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=17)),
            ],
            options={
                'db_table': 'etablissement',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('numMatiere', models.AutoField(primary_key=True, serialize=False)),
                ('nomMatiere', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'matiere',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('numSalle', models.AutoField(primary_key=True, serialize=False)),
                ('nomSalle', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'salle',
            },
        ),
        migrations.CreateModel(
            name='Edt',
            fields=[
                ('numEdt', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heureDebut', models.TimeField()),
                ('heureFin', models.TimeField()),
                ('numClasse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edt.classe')),
                ('numMatiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.matiere')),
            ],
            options={
                'db_table': 'edt',
            },
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('numAvoir', models.AutoField(primary_key=True, serialize=False)),
                ('numEdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.edt')),
                ('numEtablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.etablissement')),
            ],
            options={
                'db_table': 'avoir',
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('numMention', models.AutoField(primary_key=True, serialize=False)),
                ('nomMention', models.CharField(max_length=50)),
                ('numEtablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.etablissement')),
            ],
            options={
                'db_table': 'mention',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('numParcours', models.AutoField(primary_key=True, serialize=False)),
                ('nomParcours', models.CharField(max_length=50)),
                ('numMention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.mention')),
            ],
            options={
                'db_table': 'parcours',
            },
        ),
        migrations.AddField(
            model_name='edt',
            name='numParcours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edt.parcours'),
        ),
        migrations.CreateModel(
            name='Constituer',
            fields=[
                ('numConstituer', models.AutoField(primary_key=True, serialize=False)),
                ('numClasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.classe')),
                ('numParcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.parcours')),
            ],
            options={
                'db_table': 'constituer',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('numProfesseur', models.AutoField(primary_key=True, serialize=False)),
                ('nomProfesseur', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50, null=True)),
                ('sexe', models.CharField(max_length=1)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=17, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('numEtablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.etablissement')),
            ],
            options={
                'db_table': 'professeur',
            },
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('numEnseigner', models.AutoField(primary_key=True, serialize=False)),
                ('numMatiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.matiere')),
                ('numProfesseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.professeur')),
            ],
            options={
                'db_table': 'enseigner',
            },
        ),
        migrations.AddField(
            model_name='edt',
            name='numSalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edt.salle'),
        ),
    ]
