# Generated by Django 5.0.1 on 2025-04-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='prenomProfesseur',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
