# Generated by Django 5.0.1 on 2025-04-19 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0002_professeur_prenomprofesseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edt',
            name='numClasse',
            field=models.ForeignKey(db_column='numClasse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='edt.classe'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numMatiere',
            field=models.ForeignKey(db_column='numMatiere', on_delete=django.db.models.deletion.CASCADE, to='edt.matiere'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numParcours',
            field=models.ForeignKey(db_column='numParcours', null=True, on_delete=django.db.models.deletion.SET_NULL, to='edt.parcours'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numSalle',
            field=models.ForeignKey(db_column='numSalle', null=True, on_delete=django.db.models.deletion.SET_NULL, to='edt.salle'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='numEtablissement',
            field=models.ForeignKey(db_column='numEtablissement', on_delete=django.db.models.deletion.CASCADE, to='edt.etablissement'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='numMention',
            field=models.ForeignKey(db_column='numMention', on_delete=django.db.models.deletion.CASCADE, to='edt.mention'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='numEtablissement',
            field=models.ForeignKey(db_column='numEtablissement', on_delete=django.db.models.deletion.CASCADE, to='edt.etablissement'),
        ),
    ]
