# Generated by Django 5.0.1 on 2025-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0003_alter_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
