# Generated by Django 5.0.1 on 2025-04-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0003_alter_edt_numclasse_alter_edt_nummatiere_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissement',
            old_name='nom',
            new_name='nomEtablissement',
        ),
    ]
