# Generated by Django 5.0.1 on 2025-04-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0005_alter_professeur_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('numGroupe', models.AutoField(primary_key=True, serialize=False)),
                ('nomGroupe', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'groupe',
            },
        ),
        migrations.RemoveField(
            model_name='classe',
            name='groupe',
        ),
        migrations.CreateModel(
            name='Grouper',
            fields=[
                ('numGrouper', models.AutoField(primary_key=True, serialize=False)),
                ('numClasse', models.ForeignKey(db_column='numClasse', on_delete=django.db.models.deletion.CASCADE, to='edt.classe')),
                ('numGroupe', models.ForeignKey(db_column='numGroupe', on_delete=django.db.models.deletion.CASCADE, to='edt.groupe')),
            ],
            options={
                'db_table': 'grouper',
            },
        ),
    ]
