# Generated by Django 5.0.1 on 2025-04-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0006_groupe_remove_classe_groupe_grouper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grouper',
            new_name='Posseder',
        ),
        migrations.RenameField(
            model_name='posseder',
            old_name='numGrouper',
            new_name='numPosseder',
        ),
        migrations.AlterModelTable(
            name='posseder',
            table='posseder',
        ),
    ]
