# Generated by Django 5.0.1 on 2025-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0007_rename_grouper_posseder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcours',
            name='codeParcours',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
