# Generated by Django 5.0.1 on 2025-05-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0008_parcours_codeparcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='codeMatiere',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
