# Generated by Django 5.0.1 on 2025-05-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0009_matiere_codematiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='nomCourant',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
