# Generated by Django 5.0.1 on 2025-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0010_professeur_nomcourant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='codeMention',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
