# Generated by Django 5.0.1 on 2025-05-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0011_mention_codemention'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='photos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
