# Generated by Django 5.0.1 on 2025-05-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0012_professeur_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='maxUtilisateur',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='numEtablissement',
            field=models.ForeignKey(db_column='numEtablissement', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='edt.etablissement'),
        ),
    ]
