# Generated by Django 5.0.1 on 2025-05-10 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0013_etablissement_maxutilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='numEtablissement',
            field=models.ForeignKey(db_column='numEtablissement', on_delete=django.db.models.deletion.CASCADE, related_name='avoirs', to='edt.etablissement'),
        ),
        migrations.AlterField(
            model_name='constituer',
            name='numClasse',
            field=models.ForeignKey(db_column='numClasse', on_delete=django.db.models.deletion.CASCADE, related_name='constituers', to='edt.classe'),
        ),
        migrations.AlterField(
            model_name='constituer',
            name='numParcours',
            field=models.ForeignKey(db_column='numParcours', on_delete=django.db.models.deletion.CASCADE, related_name='constituers', to='edt.parcours'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numClasse',
            field=models.ForeignKey(db_column='numClasse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edts', to='edt.classe'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numMatiere',
            field=models.ForeignKey(db_column='numMatiere', on_delete=django.db.models.deletion.CASCADE, related_name='edts', to='edt.matiere'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numParcours',
            field=models.ForeignKey(db_column='numParcours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edts', to='edt.parcours'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numSalle',
            field=models.ForeignKey(db_column='numSalle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edts', to='edt.salle'),
        ),
        migrations.AlterField(
            model_name='enseigner',
            name='numMatiere',
            field=models.ForeignKey(db_column='numMatiere', on_delete=django.db.models.deletion.CASCADE, related_name='enseigners', to='edt.matiere'),
        ),
        migrations.AlterField(
            model_name='enseigner',
            name='numProfesseur',
            field=models.ForeignKey(db_column='numProfesseur', on_delete=django.db.models.deletion.CASCADE, related_name='enseigners', to='edt.professeur'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='numEtablissement',
            field=models.ForeignKey(db_column='numEtablissement', on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='edt.etablissement'),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='numMention',
            field=models.ForeignKey(db_column='numMention', on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='edt.mention'),
        ),
        migrations.AlterField(
            model_name='posseder',
            name='numClasse',
            field=models.ForeignKey(db_column='numClasse', on_delete=django.db.models.deletion.CASCADE, related_name='posseders', to='edt.classe'),
        ),
        migrations.AlterField(
            model_name='posseder',
            name='numGroupe',
            field=models.ForeignKey(db_column='numGroupe', on_delete=django.db.models.deletion.CASCADE, related_name='possedes', to='edt.groupe'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='numEtablissement',
            field=models.ForeignKey(db_column='numEtablissement', on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='edt.etablissement'),
        ),
    ]
