# Generated by Django 5.0.1 on 2025-05-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0015_remove_professeur_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='numEtablissement',
            field=models.ForeignKey(db_column='numEtablissement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='edt.etablissement'),
        ),
    ]
