# Generated by Django 5.0.1 on 2025-05-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0015_remove_professeur_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etablissement',
            name='maxUtilisateur',
        ),
    ]
