# Generated by Django 5.0.1 on 2025-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0016_remove_etablissement_maxutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='maxUtilisateur',
            field=models.IntegerField(default=3),
        ),
    ]
