# Generated by Django 5.0.1 on 2025-05-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0016_alter_utilisateur_numetablissement'),
        ('edt', '0017_etablissement_maxutilisateur'),
    ]

    operations = [
    ]
