# Generated by Django 5.0.1 on 2025-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0018_merge_20250511_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='lieuSalle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
