# Generated by Django 5.0.1 on 2025-05-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0019_salle_lieusalle_salle_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posseder',
            name='numGroupe',
            field=models.ForeignKey(db_column='numGroupe', on_delete=django.db.models.deletion.CASCADE, related_name='posseders', to='edt.groupe'),
        ),
    ]
