# Generated by Django 5.0.1 on 2025-05-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0020_alter_posseder_numgroupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='numClasse',
            field=models.ForeignKey(db_column='numClasse', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='edt.classe'),
        ),
        migrations.DeleteModel(
            name='Posseder',
        ),
    ]
