# Generated by Django 5.0.1 on 2025-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0021_groupe_numclasse_delete_posseder'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='groupe',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
    ]
