# Generated by Django 5.0.1 on 2025-05-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0022_classe_groupe_delete_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauParcours',
            fields=[
                ('numNiveauParcours', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=10)),
                ('numParcours', models.ForeignKey(db_column='numParcours', on_delete=django.db.models.deletion.CASCADE, related_name='niveauParcours', to='edt.parcours')),
            ],
            options={
                'db_table': 'niveauparcours',
            },
        ),
        migrations.CreateModel(
            name='Posseder',
            fields=[
                ('numPosseder', models.AutoField(primary_key=True, serialize=False)),
                ('numMatiere', models.ForeignKey(db_column='numMatiere', on_delete=django.db.models.deletion.CASCADE, related_name='posseders', to='edt.matiere')),
                ('numNiveauParcours', models.ForeignKey(db_column='numNiveauParcours', on_delete=django.db.models.deletion.CASCADE, related_name='posseders', to='edt.niveauparcours')),
            ],
            options={
                'db_table': 'posseder',
            },
        ),
    ]
