# Generated by Django 5.0.1 on 2025-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0023_niveauparcours_posseder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='photos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
