# Generated by Django 5.0.1 on 2025-05-22 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0024_alter_professeur_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='edt',
            name='numProfesseur',
            field=models.ForeignKey(db_column='numProfesseur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edts', to='edt.professeur'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numClasse',
            field=models.ForeignKey(db_column='numClasse', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edts', to='edt.classe'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numParcours',
            field=models.ForeignKey(db_column='numParcours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edts', to='edt.parcours'),
        ),
        migrations.AlterField(
            model_name='edt',
            name='numSalle',
            field=models.ForeignKey(db_column='numSalle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edts', to='edt.salle'),
        ),
    ]
