# Generated by Django 5.0.1 on 2025-08-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                ("numClasse", models.AutoField(primary_key=True, serialize=False)),
                ("niveau", models.CharField(max_length=5)),
                ("groupe", models.CharField(max_length=20, null=True)),
            ],
            options={
                "db_table": "classe",
            },
        ),
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "numEtablissement",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nomEtablissement", models.CharField(max_length=50)),
                ("adresse", models.CharField(max_length=50, null=True)),
                ("email", models.EmailField(max_length=50)),
                ("slogant", models.CharField(max_length=255, null=True)),
                ("logo", models.ImageField(upload_to="images/logo/")),
                ("contact", models.CharField(max_length=17)),
                ("maxUtilisateur", models.IntegerField(default=3)),
            ],
            options={
                "db_table": "etablissement",
            },
        ),
        migrations.CreateModel(
            name="Posseder",
            fields=[
                ("numPosseder", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "posseder",
            },
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                ("numSalle", models.AutoField(primary_key=True, serialize=False)),
                ("nomSalle", models.CharField(max_length=30)),
                ("lieuSalle", models.CharField(max_length=30, null=True)),
                ("statut", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "salle",
            },
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                ("numMention", models.AutoField(primary_key=True, serialize=False)),
                ("nomMention", models.CharField(max_length=50)),
                ("codeMention", models.CharField(max_length=20, null=True)),
                (
                    "numEtablissement",
                    models.ForeignKey(
                        db_column="numEtablissement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="etablissements.etablissement",
                    ),
                ),
            ],
            options={
                "db_table": "mention",
            },
        ),
        migrations.CreateModel(
            name="Parcours",
            fields=[
                ("numParcours", models.AutoField(primary_key=True, serialize=False)),
                ("nomParcours", models.CharField(max_length=50)),
                ("codeParcours", models.CharField(max_length=6, null=True)),
                (
                    "numMention",
                    models.ForeignKey(
                        db_column="numMention",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcours",
                        to="etablissements.mention",
                    ),
                ),
            ],
            options={
                "db_table": "parcours",
            },
        ),
        migrations.CreateModel(
            name="NiveauParcours",
            fields=[
                (
                    "numNiveauParcours",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("niveau", models.CharField(max_length=10)),
                (
                    "numParcours",
                    models.ForeignKey(
                        db_column="numParcours",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveauParcours",
                        to="etablissements.parcours",
                    ),
                ),
            ],
            options={
                "db_table": "niveauparcours",
            },
        ),
        migrations.CreateModel(
            name="Constituer",
            fields=[
                ("numConstituer", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numClasse",
                    models.ForeignKey(
                        db_column="numClasse",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constituers",
                        to="etablissements.classe",
                    ),
                ),
                (
                    "numParcours",
                    models.ForeignKey(
                        db_column="numParcours",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constituers",
                        to="etablissements.parcours",
                    ),
                ),
            ],
            options={
                "db_table": "constituer",
            },
        ),
    ]
