# Generated by Django 5.0.1 on 2025-08-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissements", "0001_initial"),
        ("professeurs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posseder",
            name="numMatiere",
            field=models.ForeignKey(
                db_column="numMatiere",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posseders",
                to="professeurs.matiere",
            ),
        ),
        migrations.AddField(
            model_name="posseder",
            name="numNiveauParcours",
            field=models.ForeignKey(
                db_column="numNiveauParcours",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posseders",
                to="etablissements.niveauparcours",
            ),
        ),
    ]
