# Generated by Django 5.0.1 on 2025-08-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissements", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="maxUtilisateur",
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
