# Generated by Django 5.0.1 on 2025-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissements", "0003_alter_etablissement_maxutilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etablissement",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/logo/"),
        ),
    ]
