# Generated by Django 5.0.1 on 2025-08-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="datenaiss",
        ),
        migrations.RemoveField(
            model_name="utilisateur",
            name="description",
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="adresse",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
