# Generated by Django 5.0.1 on 2025-08-10 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissements", "0002_initial"),
        ("professeurs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("numAction", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=20)),
                ("text", models.CharField(max_length=100, null=True)),
                ("table", models.CharField(max_length=20, null=True)),
                ("statut", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "action",
            },
        ),
        migrations.CreateModel(
            name="Edt",
            fields=[
                ("numEdt", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("heureDebut", models.TimeField()),
                ("heureFin", models.TimeField()),
                (
                    "numClasse",
                    models.ForeignKey(
                        db_column="numClasse",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edts",
                        to="etablissements.classe",
                    ),
                ),
                (
                    "numMatiere",
                    models.ForeignKey(
                        db_column="numMatiere",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edts",
                        to="professeurs.matiere",
                    ),
                ),
                (
                    "numParcours",
                    models.ForeignKey(
                        db_column="numParcours",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edts",
                        to="etablissements.parcours",
                    ),
                ),
                (
                    "numProfesseur",
                    models.ForeignKey(
                        db_column="numProfesseur",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edts",
                        to="professeurs.professeur",
                    ),
                ),
                (
                    "numSalle",
                    models.ForeignKey(
                        db_column="numSalle",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edts",
                        to="etablissements.salle",
                    ),
                ),
            ],
            options={
                "db_table": "edt",
            },
        ),
        migrations.CreateModel(
            name="Avoir",
            fields=[
                ("numAvoir", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numEtablissement",
                    models.ForeignKey(
                        db_column="numEtablissement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avoirs",
                        to="etablissements.etablissement",
                    ),
                ),
                (
                    "numEdt",
                    models.ForeignKey(
                        db_column="numEdt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="edt.edt",
                    ),
                ),
            ],
            options={
                "db_table": "avoir",
            },
        ),
    ]
