# Generated by Django 5.0.1 on 2025-08-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matiere",
            fields=[
                ("numMatiere", models.AutoField(primary_key=True, serialize=False)),
                ("nomMatiere", models.CharField(max_length=50)),
                ("codeMatiere", models.CharField(max_length=20, null=True)),
            ],
            options={
                "db_table": "matiere",
            },
        ),
        migrations.CreateModel(
            name="Professeur",
            fields=[
                ("numProfesseur", models.AutoField(primary_key=True, serialize=False)),
                ("nomProfesseur", models.CharField(max_length=50)),
                ("prenomProfesseur", models.CharField(max_length=50, null=True)),
                ("nomCourant", models.CharField(max_length=50, null=True)),
                ("grade", models.CharField(max_length=50, null=True)),
                ("sexe", models.CharField(max_length=8)),
                ("adresse", models.CharField(max_length=50, null=True)),
                ("contact", models.CharField(max_length=17, null=True)),
                ("email", models.EmailField(max_length=50, null=True)),
                (
                    "photos",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/professeurs/"
                    ),
                ),
                (
                    "numEtablissement",
                    models.ForeignKey(
                        db_column="numEtablissement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professeurs",
                        to="etablissements.etablissement",
                    ),
                ),
            ],
            options={
                "db_table": "professeur",
            },
        ),
        migrations.CreateModel(
            name="Enseigner",
            fields=[
                ("numEnseigner", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numMatiere",
                    models.ForeignKey(
                        db_column="numMatiere",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enseigners",
                        to="professeurs.matiere",
                    ),
                ),
                (
                    "numProfesseur",
                    models.ForeignKey(
                        db_column="numProfesseur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enseigners",
                        to="professeurs.professeur",
                    ),
                ),
            ],
            options={
                "db_table": "enseigner",
            },
        ),
    ]
